# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# example: https://github.com/travis-ci-examples/php
language: node_js

node_js:
  - '4'
  - '5'

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - npm install

script:
  - ./node_modules/standard/bin/cmd.js
  - /node_modules/jasmine/bin/jasmine.js
